# DAY1（读取数据）

In [1]:
import pandas as pd
import numpy as np

## Q1

读取数据（链接），并且随机跳过（skip）90%的行（seed=1）

https://github.com/datoujinggzj/WhaleDataScienceProject/blob/master/Python_data/ufo.csv

In [2]:
# 点击raw，获取raw链接才行，不然不可以直接读url
url1 = 'https://raw.githubusercontent.com/datoujinggzj/WhaleDataScienceProject/master/Python_data/ufo.csv'
np.random.seed(1)
pd.read_csv(url1,index_col = 0, skiprows = lambda x: x>0 and np.random.rand()>0.1)

               City Colors Reported Shape Reported State              Time
2           Holyoke             NaN           OVAL    CO   2/15/1931 14:00
5       Valley City             NaN           DISK    ND   9/15/1934 15:30
14        Ludington             NaN           DISK    MI    6/1/1941 13:00
26       Wilderness             NaN           DISK    WV    1/1/1944 12:00
27           Clovis             NaN           DISK    NM    4/2/1944 11:00
...             ...             ...            ...   ...               ...
18166        Mojave             NaN       TRIANGLE    CA  12/21/2000 17:54
18204     Bremerton             NaN          OTHER    WA   12/28/2000 3:00
18214        Austin             NaN      FORMATION    TX   12/29/2000 0:00
18216  Garden Grove          ORANGE          LIGHT    CA  12/29/2000 16:10
18223    Greenville             NaN            NaN    SC  12/29/2000 22:00

[1836 rows x 5 columns]

## Q2

读取数据（链接），并随机从0-100行中挑选10行去掉（seed=2022）

In [3]:
url2 = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

In [4]:
np.random.seed(2022)
pd.read_html(url2,skiprows = np.random.randint(100,size = 10))[0]

,Bank NameBank,CityCity,StateSt,CertCert,Acquiring InstitutionAI,Closing DateClosing,FundFund
0,Almena State Bank,Almena,KS,15426,Equity Bank,"October 23, 2020",10538
1,First City Bank of Florida,Fort Walton Beach,FL,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
2,The First State Bank,Barboursville,WV,14361,"MVB Bank, Inc.","April 3, 2020",10536
3,Ericson State Bank,Ericson,NE,18265,Farmers and Merchants Bank,"February 14, 2020",10535
4,City National Bank of New Jersey,Newark,NJ,21111,Industrial Bank,"November 1, 2019",10534
...,...,...,...,...,...,...,...
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001",6004
549,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001",4648
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001",4647
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000",4646
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000",4645

## Q3

读取数据（链接），爬取前5页数据

http://s.askci.com/stock/a/?reportTime=2022-06-01

In [5]:
import pandas as pd
import csv
for i in range(1,5+1):  # 爬取前5页数据
    url3 = 'http://s.askci.com/stock/a/?reportTime=2022-06-01&pageNum=%s' % (str(i))
    tb = pd.read_html(url3)[3] #网页的第4个表格
    tb.to_csv(r'day1_q3.csv', mode='a', encoding='utf_8_sig', header=1, index=0)
    print('第'+str(i)+'页DONE')

第1页DONE
第2页DONE
第3页DONE
第4页DONE
第5页DONE

In [6]:
tb

,序号,股票代码,股票简称,公司名称,省份,城市,主营业务收入(202206),净利润(202206),员工人数,上市日期,招股书,公司财报,行业分类,产品类型,主营业务
0,81,411,英特集团,浙江英特集团股份有限公司,浙江,杭州市,--,--,2800,1996-07-16,--,NaN,医药商业,医药批发、医药零售,药品、医疗器械批发及零售业务。
1,82,413,东旭光电,东旭光电科技股份有限公司,河北,石家庄市,--,--,3718,1996-09-25,--,NaN,显示器件,光电显示材料、装备及技术服务、石墨烯产业化应用、新能源汽车、建筑安装、电子通讯产品,光电显示材料、高端装备制造、新能源汽车制造。
2,83,415,渤海租赁,渤海租赁股份有限公司,新疆,乌鲁木齐市,--,--,595,1996-07-16,--,NaN,其他非银行金融,融资租赁、融资租赁咨询、经营租赁、集装箱租赁、集装箱销售、飞机销售、飞机租赁,为境内外客户提供全方位的飞机租赁、集装箱租赁、基础设施租赁、大型设备租赁等租赁服务。
3,84,416,民生控股,民生控股股份有限公司,山东,青岛市,--,--,47,1996-07-19,--,NaN,其他非银行金融,典当业务、保险经纪业务、商品零售、其他,典当业务及保险经纪业务。
4,85,417,合肥百货,合肥百货大楼集团股份有限公司,安徽,合肥市,--,--,8166,1996-08-12,--,NaN,百货,百货业（含家电）、超市业、农产品交易市场、房地产,零售业、农产品交易市场两大类业务。
5,86,419,通程控股,长沙通程控股股份有限公司,湖南,长沙市,--,--,1599,1996-08-16,--,NaN,百货,商业零售、酒店旅游,商业零售、酒店旅游、典当、保理。
6,87,420,吉林化纤,吉林化纤股份有限公司,吉林,吉林市,--,--,5120,1996-08-02,--,NaN,粘胶纤维,粘胶长丝、醋酐、粘胶短纤、亚硫酸氢钠,粘胶纤维的生产和销售。
7,88,421,南京公用,南京公用发展股份有限公司,江苏,南京市,--,--,3061,1996-08-06,--,NaN,燃气,汽车营运、房产开发、汽车销售、旅游服务、燃气销售、工程施工,燃气销售、房地产开发及客运产业。
8,89,422,湖北宜化,湖北宜化化工股份有限公司,湖北,宜昌市,--,--,7998,1996-08-15,--,NaN,氮肥,尿素、精细化工产品、电力产品、氯碱产品、聚氯乙烯、磷酸二铵、贸易业务,化肥产品(尿素、磷酸二铵等)、化工产品(聚氯乙烯、烧碱等)的生产、销售。
9,90,423,东阿阿胶,东阿阿胶股份有限公司,山东,聊城市,--,--,4180,1996-07-29,--,NaN,中药生产,阿胶及系列产品、医药贸易、其他药品及保健品、毛驴养殖及销售、其他,从事阿胶及阿胶系列产品的研发、生产和销售。
10,91,425,徐工机械,徐工集团工程机械股份有限公司,江苏,徐州市,--,--,15483,1996-08-28,--,NaN,工程机械,工程机械,主要从事工程起重机械、铲运机械、压实机械、混凝土机械、路面机械、消防机械、其他工程机械及工程...
11,92,426,兴业矿业,内蒙古兴业矿业股份有限公司,内蒙古,赤峰市,--,--,673,1996-08-28,--,NaN,铅锌,锌精粉、铁精粉、铅精粉、钨精粉、含铅银精粉、含铜银精粉、锡精粉,有色金属采选及冶炼。
12,93,428,华天酒店,华天酒店集团股份有限公司,湖南,长沙市,--,--,3354,1996-08-08,--,NaN,酒店,酒店业、房地产业、酒店资产运营,酒店服务业。
13,94,429,粤高速A,广东省高速公路发展股份有限公司,广东,广州市,--,--,2983,1998-02-20,--,NaN,高速公路,公路运输,收费高速公路、桥梁的投资、建设、收费和养护管理。
14,95,430,张家界,张家界旅游集团股份有限公司,湖南,张家界市,--,--,1027,1996-08-29,--,NaN,景区,旅行社服务、旅游客运、旅游服务、酒店服务、租赁服务、销售服务,旅游项目经营；旅游客运；旅行社经营；其他：酒店经营、房屋租赁、广告代理等。
15,96,488,晨鸣纸业,山东晨鸣纸业集团股份有限公司,山东,潍坊市,--,--,12296,2000-11-20,--,NaN,造纸,制浆、造纸,机制纸及板纸和造纸原料、造纸机械、电力、热力的生产与销售
16,97,498,山东路桥,山东高速路桥集团股份有限公司,山东,济南市,--,--,24686,1997-06-09,--,NaN,路桥建设,路桥工程施工、路桥养护施工、周转材料及设备租赁销售、商品混凝土加工销售、工程设计咨询,路桥工程施工与养护施工。
17,98,501,武商集团,武商集团股份有限公司,湖北,武汉市,--,--,9373,1992-11-20,--,NaN,百货,商品销售,从事购物中心及超市业态的商品销售业务。
18,99,502,绿景退,绿景控股股份有限公司,广东,广州市,--,--,148,1992-11-23,--,NaN,房地产开发,房地产业(房产销售及租赁)、房地产业(物业管理)、医疗服务,从事房地产开发及物业管理业务、互联网数据中心业务。
19,100,503,国新健康,国新健康保障服务集团股份有限公司,海南,海口市,--,--,1572,1992-11-30,--,NaN,电子商务B2B,大健康服务,医药电子商务、医疗福利管理等。